pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M8'
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'micronaut-graal-languages'

include 'graalpy'
include 'graal-languages-bom'
include 'test-suite-graalpy'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames=true
    importMicronautCatalog()
}
