plugins {
    id("io.micronaut.build.internal.graal-languages-module")
}

dependencies {
    api(libs.managed.graalpy) {
        artifact {
            type = "pom"
        }
        transitive = true
    }
    api(libs.managed.graalpy.embedding)

    constraints {
        implementation("org.bouncycastle:bcpkix-jdk18on:1.84") {
            because("Older versions have security vulnerabilities")
        }
    }

    implementation(mn.micronaut.aop)
}

micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.graalpy:micronaut-graalpy"
    }
}
